# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/a7-35t.xdc

# XDC: new/master.xdc

# Block Designs: bd/seq_probe/seq_probe.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe || ORIG_REF_NAME==seq_probe} -quiet] -quiet

# IP: bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_c_counter_binary_0_0 || ORIG_REF_NAME==seq_probe_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/seq_probe/ip/seq_probe_divider_0_0/seq_probe_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_divider_0_0 || ORIG_REF_NAME==seq_probe_divider_0_0} -quiet] -quiet

# IP: bd/seq_probe/ip/seq_probe_encoding_sequencer_0_0/seq_probe_encoding_sequencer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_encoding_sequencer_0_0 || ORIG_REF_NAME==seq_probe_encoding_sequencer_0_0} -quiet] -quiet

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_0/design_2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_0 || ORIG_REF_NAME==design_2_microblaze_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_v10_0/design_2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_0 || ORIG_REF_NAME==design_2_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_v10_0/design_2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_0 || ORIG_REF_NAME==design_2_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_0/design_2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_0/design_2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_lmb_bram_0/design_2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_0 || ORIG_REF_NAME==design_2_lmb_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_axi_periph_0/design_2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_axi_intc_0/design_2_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_2_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_0_xlconcat_0/design_2_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_2_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mdm_1_0/design_2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_mdm_1_0 || ORIG_REF_NAME==design_2_mdm_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_0 || ORIG_REF_NAME==design_2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_clk_wiz_1_100M_0/design_2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_seq_probe_wrapper_0_0/design_2_seq_probe_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_seq_probe_wrapper_0_0 || ORIG_REF_NAME==design_2_seq_probe_wrapper_0_0} -quiet] -quiet

# Block Designs: bd/seq_probe/seq_probe.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe || ORIG_REF_NAME==seq_probe} -quiet] -quiet

# IP: bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_c_counter_binary_0_0 || ORIG_REF_NAME==seq_probe_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/seq_probe/ip/seq_probe_divider_0_0/seq_probe_divider_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_divider_0_0 || ORIG_REF_NAME==seq_probe_divider_0_0} -quiet] -quiet

# IP: bd/seq_probe/ip/seq_probe_encoding_sequencer_0_0/seq_probe_encoding_sequencer_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_encoding_sequencer_0_0 || ORIG_REF_NAME==seq_probe_encoding_sequencer_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_QCS_AXI_0_0/design_2_QCS_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_QCS_AXI_0_0 || ORIG_REF_NAME==design_2_QCS_AXI_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_QCS_0_0/design_2_QCS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_QCS_0_0 || ORIG_REF_NAME==design_2_QCS_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_0/design_2_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ila_0_0 || ORIG_REF_NAME==design_2_ila_0_0} -quiet] -quiet

# Block Designs: bd/QCS_1/QCS_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_1 || ORIG_REF_NAME==QCS_1} -quiet] -quiet

# IP: bd/QCS_1/ip/QCS_1_QCS_0_1/QCS_1_QCS_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==QCS_1_QCS_0_1 || ORIG_REF_NAME==QCS_1_QCS_0_1} -quiet] -quiet

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/seq_probe/seq_probe_ooc.xdc

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/seq_probe/seq_probe_ooc.xdc

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/design_2/design_2_ooc.xdc

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/QCS_1/QCS_1_ooc.xdc
