# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/design_2/ip/design_2_seq_probe_wrapper_0_0/design_2_seq_probe_wrapper_0_0.xci
# IP: The module: 'design_2_seq_probe_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/seq_probe.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe || ORIG_REF_NAME==seq_probe} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_c_counter_binary_0_0 || ORIG_REF_NAME==seq_probe_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_divider_0_0/seq_probe_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_divider_0_0 || ORIG_REF_NAME==seq_probe_divider_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_encoding_sequencer_0_0/seq_probe_encoding_sequencer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_encoding_sequencer_0_0 || ORIG_REF_NAME==seq_probe_encoding_sequencer_0_0} -quiet] -quiet

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/seq_probe/seq_probe_ooc.xdc

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/design_2/ip/design_2_seq_probe_wrapper_0_0/design_2_seq_probe_wrapper_0_0.xci
# IP: The module: 'design_2_seq_probe_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/seq_probe.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe || ORIG_REF_NAME==seq_probe} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_c_counter_binary_0_0 || ORIG_REF_NAME==seq_probe_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_divider_0_0/seq_probe_divider_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_divider_0_0 || ORIG_REF_NAME==seq_probe_divider_0_0} -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_encoding_sequencer_0_0/seq_probe_encoding_sequencer_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seq_probe_encoding_sequencer_0_0 || ORIG_REF_NAME==seq_probe_encoding_sequencer_0_0} -quiet] -quiet

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/seq_probe/seq_probe_ooc.xdc
