# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0.xci
# IP: The module: 'seq_probe_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seq_probe_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/duncan/QCS/QCS.srcs/sources_1/bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0.xci
# IP: The module: 'seq_probe_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duncan/QCS/QCS.gen/sources_1/bd/seq_probe/ip/seq_probe_c_counter_binary_0_0/seq_probe_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seq_probe_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
